apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygo-app
  labels:
    app: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-cont
        image: ibrarullah/goapp:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: go-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: go-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: port
          valueFrom:
            configMapKeyRef:
              name: go-config
              key: PORT
        ports:
        - containerPort: 4040
