apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygo-app
  labels:
     app: go-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-cont
        image: ibrarullah/goapp:latest
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: root
        - name: port
          value: "4040"
        ports:
        - containerPort: 4040